[package]
name = "heappy"
version = "0.1.0"
authors = [ "Marko Mikulicic <mkm@influxdata.com>" ]
edition = "2018"

[workspace]
members = [
    "examples/complex",
    "examples/simple",
]

[profile.release]
debug = true

[features]
default = []
jemalloc_shim = [ "tikv-jemalloc-sys" ]
enable_heap_profiler = [ "jemalloc_shim" ]
measure_free = []

[dependencies]
backtrace = "0.3.63"
bytes = "1.1.0"
lazy_static = "1.4.0"
libc = { version = "^0.2.112", default-features = false }
pprof = {version = "^0.6", features = [ "flamegraph", "protobuf" ] }
prost = "0.8"
spin = "0.9.2"
tikv-jemalloc-sys = { version = "0.4", optional = true, features = [ "stats" ] }
thiserror = "^1"
